//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathPlus.Models
{
    using Main.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaAdvertisementPhoto))]
    public partial class AdvertisementPhoto
    {
        public long AdPhotoSN { get; set; }
        public string Photo { get; set; }
        public string AdvertisementID { get; set; }
    
        public virtual Advertisement Advertisement { get; set; }
    }
}
