//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draw
    {
        public string MemberID { get; set; }
        public string CardID { get; set; }
        public System.DateTime Date { get; set; }
        public string DrawMemberID { get; set; }
        public string PairingStatusID { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual PairingStatusCategory PairingStatusCategory { get; set; }
        public virtual Member Member { get; set; }
    }
}
