//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathPlus.Models
{
    using Main.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaGroupPost))]
    public partial class GroupPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupPost()
        {
            this.CommentGroupPost = new HashSet<CommentGroupPost>();
            this.GroupPostPhoto = new HashSet<GroupPostPhoto>();
        }
    
        public string GroupPostID { get; set; }
        public string Content { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime EditDate { get; set; }
        public string MemberID { get; set; }
        public string GroupID { get; set; }
        public string StatusCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentGroupPost> CommentGroupPost { get; set; }
        public virtual Group Group { get; set; }
        public virtual Member Member { get; set; }
        public virtual GroupPostStatusCategory GroupPostStatusCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupPostPhoto> GroupPostPhoto { get; set; }
    }
}
