//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathPlus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PathPlusEntities : DbContext
    {
        public PathPlusEntities()
            : base("name=PathPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<AdministratorAuthorityCategory> AdministratorAuthorityCategory { get; set; }
        public virtual DbSet<AdvertisemenStatusCategory> AdvertisemenStatusCategory { get; set; }
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<AdvertisementPhoto> AdvertisementPhoto { get; set; }
        public virtual DbSet<Advertisers> Advertisers { get; set; }
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<AnnouncementStatusCategory> AnnouncementStatusCategory { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<CardStatusCategory> CardStatusCategory { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<CommentGroupPost> CommentGroupPost { get; set; }
        public virtual DbSet<Draw> Draw { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupAuthorityCategory> GroupAuthorityCategory { get; set; }
        public virtual DbSet<GroupManagement> GroupManagement { get; set; }
        public virtual DbSet<GroupPost> GroupPost { get; set; }
        public virtual DbSet<GroupPostPhoto> GroupPostPhoto { get; set; }
        public virtual DbSet<GroupPostStatusCategory> GroupPostStatusCategory { get; set; }
        public virtual DbSet<GroupPrivateCategory> GroupPrivateCategory { get; set; }
        public virtual DbSet<JoinGroup> JoinGroup { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberAccountStatusCategory> MemberAccountStatusCategory { get; set; }
        public virtual DbSet<MemberPrivateCategory> MemberPrivateCategory { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<PairingStatusCategory> PairingStatusCategory { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostCategory> PostCategory { get; set; }
        public virtual DbSet<PostPhoto> PostPhoto { get; set; }
        public virtual DbSet<PostStatusCategory> PostStatusCategory { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Relationship> Relationship { get; set; }
        public virtual DbSet<Term> Term { get; set; }
        public virtual DbSet<TermStatusCategory> TermStatusCategory { get; set; }
    }
}
