//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathPlus.Models
{
    using Main.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaRelationship))]
    public partial class Relationship
    {
        public long RelationshipSN { get; set; }
        public System.DateTime FollowDate { get; set; }
        public System.DateTime BlockDate { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string Reason { get; set; }
        public string MemberID { get; set; }
        public string RSMemberID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
